### ISSUE TITLE
Weird co-authorship...

### ISSUE THREAD

**Issue by ghost** [tomschr/xml-format-action#21]
https://github.com/SUSE/doc-ses/commit/f5246e545252885483015e69794cf14bb0b77d00 has this:

`Co-authored-by: "Julia Faltenbacher" <sknorr@users.noreply.github.com>`

1. Neither Julia nor I authored or co-authored the commit. It's rather unwelcome when the bot claims that we did. Especially when the commit as unnecessary as the above one. 
2. Julia is not me. I am not Julia. She made the original commits, I pushed them. The bot somehow adds her name to an (auto-generated) email address of mine.

**Comment by tomschr** [comment]
This seems to be fixed now. Co-authorship looks like:

    Co-authored-by: "Tomáš" <tbazant@users.noreply.github.com>
